name: Shell Commands

on:
  push:
      branches: [rrfs_ci_simple]
  workflow_dispatch:

defaults:
  run:
    shell: bash -leo pipefail {0}

jobs: 
  run-shell-command:
    runs-on: ubuntu-latest
    steps:
      - name: echo a string
        run: echo "Hello World"
      - name: multiline script
        run: |
          node -v
          pwd
      - name: python command
        run: |
          import platform
          print (platform.processor())
        shell: python
