name: Shell Commands

on:
  push:
      branches: [rrfs_ci_simple]
  workflow_dispatch:

defaults:
  run:
    shell: bash -leo pipefail {0}

jobs: 
  run-shell-command:
    runs-on: ubuntu-20.04
    name: job_run
    env:
      DB_DATABASE: mv_ci
      DB_USER: root
      DB_PASSWORD: 'root'
      DB_HOST: localhost
    steps:
      - name: echo a string
        run: echo "Hello World"
      - name: check out code
        uses: actions/checkout@main
      - name: start mysql
        run: |
          sudo systemctl start mysql
          mysql -e 'CREATE DATABASE mv_ci;' -uroot -proot
          mysql -e 'SHOW DATABASES;' -uroot -proot
          mysql -e 'SOURCE /home/runner/work/testmysql/testmysql/sql/mv_mysqlt.sql;'  -uroot -proot mv_ci
      - name: multiline script
        run: |
          node -v
          pwd
          pip install numpy
          pip install pandas
          pip install pymysql
          pip install lxml
          ls -l /home/runner/work/testmysql/testmysql/sql/mv_mysql.sql
      - name: python command
        run: |
          import platform
          print (platform.processor())
          import argparse
          import logging
          import time
          from datetime import datetime
          from datetime import timedelta
          import pymysql
          import numpy
          import pandas
          import lxml
          import sys
          import os
          conn = pymysql.connect(host='localhost',port=3306,user='root',passwd='root',db='mv_ci')
          cur = conn.cursor()
          cur.execute('select database();')
          print(cur.fetchall())
          cur.execute('show databases;')
          print(cur.fetchall())
          cur.execute('show tables;')
          print(cur.fetchall())
        shell: python
